name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0'

permissions:
  contents: read

jobs:
  test-install:
    name: Install test
    runs-on: docker
    container:
      image: node:20-bullseye
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.0.0
          - 1.62.0
          - stable
          - beta
          - nightly
          - stable 18 months ago
          - stable minus 8 releases          
    timeout-minutes: 45
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run test
        uses: ./tests/install
        with:
          toolchain: ${{matrix.rust}}

  test-default:
    name: Default test
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run test
        uses: ./tests/default

  test-override:
    name: Override test
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run test
        uses: ./tests/override

  test-profile:
    name: Profile test
    runs-on: docker
    container:
      image: node:20-bullseye
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Run test
        uses: ./tests/profile
