name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0'

permissions:
  contents: read

jobs:
  test:
    name: Rust ${{matrix.rust}} on ${{matrix.os == 'ubuntu' && 'Linux' || matrix.os == 'macos' && 'macOS' || matrix.os == 'windows' && 'Windows' || 'unknown'}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        rust:
          - nightly
          - beta
          - stable
          - 1.62.0
          - stable 18 months ago
          - stable minus 8 releases
        include:
          - os: ubuntu
            rust: 1.0.0
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: ./tests
        with:
          toolchain: ${{matrix.rust}}
