name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0'

permissions:
  contents: read

jobs:
  test-install:
    name: Install test
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - 1.62.0
          - stable
          - beta
          - nightly
          - stable 18 months ago
          - stable minus 8 releases   
        include:
          - os: ubuntu-latest
            rust: 1.0.0
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        uses: ./tests/install
        with:
          toolchain: ${{matrix.rust}}

  test-default:
    name: Default test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        uses: ./tests/default

  test-override:
    name: Override test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        uses: ./tests/override

  test-profile:
    name: Profile test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run test
        uses: ./tests/profile
